spring:
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
      datasource:
        ds:
          nacos:
            rule-type: flow
            server-addr: localhost:8848
            dataId: sentinel-datasource-nacos
            groupId: DEFAULT_GROUP
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: javatips-springcloud-consumer-goodsorder # 路由的 ID 需要唯一
          uri: lb://javatips-springcloud-consumer-goodsorder # 匹配后路由地址 lb代表从注册中心获取服务，lb是Load Balance的缩写
          # 路由（routing）就是通过互联的网络把信息从源地址传输到目的地址的活动
          predicates: # 路由条件
            - Path=/order/**
          filters:
            - StripPrefix=1

        - id: javatips-springcloud-provider-user-biz
          uri: lb://javatips-springcloud-provider-user-biz
          predicates:
            - Path=/appuser/**
          filters:
            - StripPrefix=1
logging:
  level:
    org.springframework.cloud.gateway: debug
